#!/bin/bash
set -ex

# Check for Homebrew and install if we don't have it
if test ! $(which brew); then
    echo "Installing Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

echo "Setting up your Mac..."

./brew_install

if test $(which fisher); then
    fisher install
fi

# Initialize dotfiles chezmoi config (separate from pi-config's chezmoi)
chezmoi init --config-path ~/.config/chezmoi-dotfiles/chezmoi.yaml --source ~/dev/dotfiles/home --apply=false

# Apply dotfiles
chezmoi --config ~/.config/chezmoi-dotfiles/chezmoi.yaml apply

# Set macOS preferences
# We will run this last because this will reload the shell
source .macos

sudo echo "$(which fish)" >> /etc/shells
chsh -s $(which fish)
