#!/bin/bash
set -x
echo "Setting up your Mac..."

./brew_install

if test $(which fisher); then
    fisher install
# fisher update
fi
# Symlink the Mackup config file to the home directory
# ln -s $HOME/.dotfiles/.mackup.cfg $HOME/.mackup.cfg

stow --target=/Users/$(whoami)/.config .config/

stow --target=/Users/$(whoami)/ .home/

# Set macOS preferences
# We will run this last because this will reload the shell
source .macos

sudo echo "$(which fish)" >> /etc/shells
chsh -s $(which fish)