[bootstrap.packages]
"brew-cask:font-jetbrains-mono" = { version = "latest", os = "macos" }
"brew-cask:rectangle" = { version = "latest", os = "macos" }

[dotfiles]
"~/.config/fish/user_conf.d/stripe.fish" = "~/dev/dotfiles/profiles/work/.config/fish/user_conf.d/stripe.fish"
