model = "gpt-5.4"
model_reasoning_effort = "medium"
[projects."/Users/adaminglehart/dev/agent"]
trust_level = "trusted"

[projects."/Users/adaminglehart/dev/dotfiles"]
trust_level = "trusted"

[projects."/Users/adaminglehart/stripe/dev/dotfiles"]
trust_level = "trusted"

[projects."/Users/adaminglehart/stripe/dev/privy"]
trust_level = "trusted"
